services:
  - type: web
    name: formix-respaldo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: SESSION_COOKIE_SECURE
        value: 1
      - key: APP_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: formix-db
          property: connectionString
      - key: TZ
        value: America/Cancun
databases:
  - name: formix-db
    databaseName: formix
    user: formix_user
